### ISSUE TITLE
banti vs chamanti

### ISSUE THREAD

**Issue by ChillarAnand** [rakeshvar/telugu_ocr_banti#10]
There is a seperate ocr in your github https://github.com/rakeshvar/chamanti_ocr.

Are there any advantages of using chamanti instead banti?

**Comment by rakeshvar** [comment]
చామంతి is the next generation, supposed to be a much better system. Of course it is an ambitious project with lot of scope. It is still in early stages of development. I do not have much time to work on it now. But if you want to learn Deep Learning and take it forward, I can help you.

**Comment by ChillarAnand** [comment]
Thank you. That will be great.

**Comment by ChillarAnand** [comment]
Can you suggest some good resources to learn machine/deep learning?

**Comment by rakeshvar** [comment]
Banti is based on Convolutional Neural Networks. Which can be learnt from [CS231N](http://vision.stanford.edu/teaching/cs231n/).

Chamanti is based on Recurrent Neural Networks. For which a good reference is at [References section of rnn_ctc](https://github.com/rakeshvar/rnn_ctc)(Bottom of page).
