### ISSUE TITLE
Training data and the CNN training file.

### ISSUE THREAD

**Issue by mano143** [rakeshvar/telugu_ocr_banti#6]
I am interested in doing the project. Can you please make the training data and the theano training file for banti avaiable to us.
Regards

**Comment by rakeshvar** [comment]
ok.

**Comment by mano143** [comment]
Dhanyavaadalu Rakeshgaru for uploading Corpus Data. 
Regards

**Comment by mano143** [comment]
You are really kind. Got the CNN training part too!! Rakeshgaaru meeku kruthagyathalu.
Regards

**Comment by rakeshvar** [comment]
Where did you get the training data from? I am still thinking where to place it, as it is a 10MB file.

**Comment by mano143** [comment]
Can you please send it to my mail address if possible, ruthwik.classes@gmail.com.

Regards
