### ISSUE TITLE
pls provide banti_segmenter binary  for mac osx

### ISSUE THREAD

**Issue by wanghaisheng** [rakeshvar/telugu_ocr_banti#7]

**Comment by rakeshvar** [comment]
I do not have access to a Mac, if you can download the source code and compile and upload a binary, that would be awesome :)

**Comment by rakeshvar** [comment]
`page.py` in the `banti` module of release `v2.0` does everything that `banti_segmenter` can do. The `banti_segmenter` has been renamed `antanci_telugu_ocr`.
